[project]
name = "tradescouts-api"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "Django>=5,<6.0",
]

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"

[tool.uv]
package = false
